
server:
  port: 1111
  
spring:
  application:
    name: hiClient1
    
 ##if not default port no 8761 to server then client willnot find for server
 #need to configure port to find server
 
#eureka:
#  client:
#   service-url:
#      defaultZone:${DISCOVERY_URL:http://localhost:"Eureka Server port"}/eureka/
    
